In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<b><font sixe="8" color="red">ch11.데이터프레임과 시리즈(pandas) </font></b>

# 1절 판다스 패키지
- 데이터 분석을 위해 반드시 알아야 할 패키지. 넘파이 기반으로 다른 많은 라이브러리와 잘 통합되도록 설계 
- 1차원 구조를 가지는 시리즈, 2차원 구조를 가지는 데이터프레임(엑셀의 스프레드시트)을 제공
- 판다스 장점: 파일 io, 부분 데이터 추추, 킈변경, 데이터분할, 병합, 결측치 처리, 데이터분할, 피벗과 언피벗(와이드 포맷과 롱포맷)에 용이 
- [pandas API reference] (https://pandas.pydata.org/docs/reference/index.html)
- [pandas docs] (https://pandas.pydata.org/docs/)

In [2]:
import pandas as pd
pd.__version__

'1.5.3'

In [7]:
data = pd.read_csv('data/ch09_member4.csv')
display(data)

name  age    email address
0  홍길동   22  a@a.com     신림동
1  신길동   32  b@a.com     신림동
2  김길동   42  c@a.com     신림동

In [11]:
data = pd.read_csv('data/ch09_member1.csv',header=None, 
                    names=['name','age','email','address'])
data
data.head(2) #최초 상위 2줄 

name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구

In [14]:
data = pd.read_json('data/ch09_member1.json') #기본값이 utf-8
data

name  age    email address
0  홍길동   22  a@a.com      서울
1  신길동   32  a@a.com      서울
2  김길동   42  a@a.com      서울

In [17]:
iris = pd.read_hdf('data/ch09_iris.hdf5', key = 'iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# 2절 데이터 프레임 만들기
## 2.1 딕셔너리를 이용해서 데이터프레임 열기

In [18]:
d= {'kor':[100,90], 'mat':[95,99]} #딕셔너리를 데이터프레임으로
df = pd.DataFrame(data=d)
df

kor  mat
0  100   95
1   90   99

In [19]:
df.to_dict()

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [20]:
df.to_numpy()

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [22]:
#딕셔너리 라스트를 데이터프레임
d= [{'kor':100, 'mat':95} ,{'kor':90, 'mat':99}]
df = pd.DataFrame(data=d)
df

kor  mat
0  100   95
1   90   99

In [24]:
df.dtypes

kor    int64
mat    int64
dtype: object

In [25]:
df.info() # 얘를 더 많이씀 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [29]:
d= [{'kor':100, 'mat':95} ,{'kor':90, 'mat':99}, {'kor':93, 'eng':100}]
df = pd.DataFrame(data=d)   #결측치는 실수형 , 정수형변환 불가(경측치대체를 한후 정수형 변화)
df

kor   mat    eng
0  100  95.0    NaN
1   90  99.0    NaN
2   93   NaN  100.0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     3 non-null      int64  
 1   mat     2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 176.0 bytes


## 2.2 리스트를 이용해서 데이터 프레임 열기

In [35]:
title = ['책1','책2','책3']
price = [15000, 18000, 10000]
df = pd.DataFrame(data={'title':title, 'price':price})
df

title  price
0    책1  15000
1    책2  18000
2    책3  10000

In [36]:
import numpy as np
np.c_[title, price]

array([['책1', '15000'],
       ['책2', '18000'],
       ['책3', '10000']], dtype='<U11')

In [37]:
df = pd.DataFrame(np.c_[title, price], columns=['책이름','가격'])
df

책이름     가격
0  책1  15000
1  책2  18000
2  책3  10000

In [34]:
l= [['책1',15000],
    ['책2',18000],
   ['책3',10000]]
df = pd.DataFrame(l,columns=['책이름','가격'])
df

책이름     가격
0  책1  15000
1  책2  18000
2  책3  10000

In [40]:
%ls C:\ai_x\download\상가정보_20250331

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 3664-591E

 C:\ai_x\download\상가정보_20250331 디렉터리

2025-04-28  오후 03:53    <DIR>          .
2025-04-28  오후 03:53    <DIR>          ..
2025-04-27  오후 11:07             1,011 [필독]파일열람방법.txt
2025-04-27  오후 11:07        61,227,944 소상공인시장진흥공단_상가(상권)정보_강원_202503.csv
2025-04-27  오후 11:07       356,572,082 소상공인시장진흥공단_상가(상권)정보_경기_202503.csv
2025-04-27  오후 11:07        93,472,559 소상공인시장진흥공단_상가(상권)정보_경남_202503.csv
2025-04-27  오후 11:07        76,425,275 소상공인시장진흥공단_상가(상권)정보_경북_202503.csv
2025-04-27  오후 11:07        40,070,868 소상공인시장진흥공단_상가(상권)정보_광주_202503.csv
2025-04-27  오후 11:07        61,715,005 소상공인시장진흥공단_상가(상권)정보_대구_202503.csv
2025-04-27  오후 11:07        41,491,092 소상공인시장진흥공단_상가(상권)정보_대전_202503.csv
2025-04-27  오후 11:07        84,550,600 소상공인시장진흥공단_상가(상권)정보_부산_202503.csv
2025-04-27  오후 11:07       294,549,483 소상공인시장진흥공단_상가(상권)정보_서울_202503.csv
2025-04-27  오후 11:07         9,303,432 소상공인시장진흥공단_상가(상권)정보_세종_202503.csv
2025-04-27  오후 11:07        28,457,489 소상공인시장진흥공단

In [46]:
df= pd.read_csv(r'C:/ai_x/download/상가정보_20250331/소상공인시장진흥공단_상가(상권)정보_경기_202503.csv',
                low_memory=False,
                nrows=30) #처음 30행만
                
df.shape

(30, 39)

In [47]:
df.head(1)

상가업소번호     상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드   상권업종중분류명  \
0  MA010120220800000037  PENIEL  NaN        G2       소매      G217  시계·귀금속 소매   

  상권업종소분류코드    상권업종소분류명 표준산업분류코드  ...                     건물관리번호  건물명  \
0    G21701  시계/귀금속 소매업   G47830  ...  4115010100101320039021620  NaN   

                도로명주소   구우편번호  신우편번호  동정보  층정보  호정보          경도         위도  
0  경기도 의정부시 시민로 132-1  480011  11697  NaN  NaN  NaN  127.049748  37.737903  

[1 rows x 39 columns]

In [49]:
#판다스 디스플레이 옵션 
pd.options.display.max_columns = 40 #39열까지 display 가능(기본값20)
pd.options.display.max_rows = 40 #40행까지 display 가능(기본값 60)

In [50]:
df.head(1)

상가업소번호     상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드   상권업종중분류명  \
0  MA010120220800000037  PENIEL  NaN        G2       소매      G217  시계·귀금속 소매   

  상권업종소분류코드    상권업종소분류명 표준산업분류코드       표준산업분류명  시도코드  시도명  시군구코드  시군구명  \
0    G21701  시계/귀금속 소매업   G47830  시계 및 귀금속 소매업    41  경기도  41150  의정부시   

      행정동코드   행정동명       법정동코드  법정동명                 지번코드  대지구분코드 대지구분명  \
0  41150510  의정부1동  4115010100  의정부동  4115010100101320039       1    대지   

   지번본번지  지번부번지                  지번주소         도로명코드           도로명  건물본번지  \
0    132   39.0  경기도 의정부시 의정부동 132-39  411503181060  경기도 의정부시 시민로    132   

   건물부번지                     건물관리번호  건물명               도로명주소   구우편번호  신우편번호  \
0    1.0  4115010100101320039021620  NaN  경기도 의정부시 시민로 132-1  480011  11697   

   동정보  층정보  호정보          경도         위도  
0  NaN  NaN  NaN  127.049748  37.737903

In [51]:
#(1) CSV 파일 불러오기(기본값)
# encoding = utf-8, sep=',' csv파일의 첫번째 줄을 header #이 있는 줄도 데이터로 인식
member = pd.read_csv('data/ch11_member.csv')
member

Name  Age          Email  Address       Birth
0   홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1   홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2   홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3   홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4   홍길중   23   mid@hong.com   부산시 중구  1999-01-30
5  #홍길뜽   24    non@not.com      없는구  2000-01-01

In [52]:

member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int64 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes


In [53]:
# 형변환 Age열:int64 -> int16
member['Age'] = member['Age'].astype(np.int16) # 'int' : np.int32
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int16 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int16(1), object(4)
memory usage: 332.0+ bytes


In [54]:
# 형변환 Birth열 : object(문자) -> datetime64
member['Birth_as'] = member['Birth'].astype('datetime64')
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Name      6 non-null      object        
 1   Age       6 non-null      int16         
 2   Email     6 non-null      object        
 3   Address   6 non-null      object        
 4   Birth     6 non-null      object        
 5   Birth_as  6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int16(1), object(4)
memory usage: 380.0+ bytes


In [55]:
member['Birth_to'] = pd.to_datetime(member['Birth']) #astype() 함수보다 안전한 형변환 
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Name      6 non-null      object        
 1   Age       6 non-null      int16         
 2   Email     6 non-null      object        
 3   Address   6 non-null      object        
 4   Birth     6 non-null      object        
 5   Birth_as  6 non-null      datetime64[ns]
 6   Birth_to  6 non-null      datetime64[ns]
dtypes: datetime64[ns](2), int16(1), object(4)
memory usage: 428.0+ bytes


In [56]:
# (2) 특정행 제외하고 csv파일읽기
member = pd.read_csv('data/ch11_membercp949.csv',
                    encoding='cp949',
                    skiprows=[1, 6]) # 1,6번째 행은 제외하고 읽어오기
member

Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [70]:
# (3) 주석(#)제외, datetime형 필드 지정하여 읽기
member = pd.read_csv('data/ch11_membertab.csv',
                    sep='\t',
                    comment='#',
                    parse_dates=['Birth']) # datetime형으로 읽어올 필드 지정
member

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [71]:
# (4) sep='|', 상위5행만 읽어오기
member = pd.read_csv('data/ch11_membersep.csv',
                    sep='|',
                    nrows=5)
member

Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구  1999-01-30

## 2.4 패키지에서 가져오기 : iris 데이터
- iris 가져오기 방법 1 : sklearn(머신러닝패키지)
-  iris 가져오기 방법 2: statsmodels (R데이터)
-  iris 가져오기 방법 3: seaborn(시각화패키지)

##  iris 가져오기 방법 1 : sklearn(머신러닝패키지)

In [58]:
from sklearn import datasets
#sklearn : 머신러닝패키지(전처리,머신러닝, 성능평가를 위한 함수, 함습데이터셋)
iris = datasets.load_iris()
iris.keys() #딕셔너리 형태 

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [59]:
iris.data #독립변수
iris['data'][:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [61]:
iris.feature_names #독립변수 열이름
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [74]:
#데이터 프레임에서 열이름 
columns = [col[:-5].replace(' ','_') for col in iris.feature_names]+['spacies']

In [64]:
iris.target
iris['target'] #머신러닝 시 종속변수

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [65]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [66]:
iris.target_names[iris.target]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [67]:
#독립변수
data = iris.data
target = iris.target_names[iris.target]
data.shape, target.shape #독립변수와 종속변수의 차원

((150, 4), (150,))

In [75]:
# 독립변수와 종속변수를 stack한 후 데이터 프레임으로
pd.DataFrame(data = np.hstack( (data, target.reshape(-1,1) ) ),
            columns=columns)

sepal_length sepal_width petal_length petal_width    spacies
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]